import type { ThreatReport } from "@threat-modeller/core";

export function generateMarkdown(report: ThreatReport): string {
  const lines: string[] = [];

  lines.push("# ThreatLens Security Analysis Report");
  lines.push("");
  lines.push(`**Generated:** ${new Date(report.generatedAt).toLocaleString()}`);
  lines.push(`**Model:** ${report.metadata.provider} / ${report.metadata.model}`);
  lines.push(`**Analysis Duration:** ${(report.metadata.totalDurationMs / 1000).toFixed(1)}s`);
  lines.push("");

  lines.push("## Architecture Summary");
  lines.push("");
  lines.push(report.architectureSummary);
  lines.push("");

  if (report.assumptionsMade.length > 0) {
    lines.push("## Assumptions Made");
    lines.push("");
    for (const assumption of report.assumptionsMade) {
      lines.push(`- ${assumption}`);
    }
    lines.push("");
  }

  lines.push("## Threat Summary");
  lines.push("");
  lines.push("| # | Title | STRIDE | Component | DREAD |");
  lines.push("|---|-------|--------|-----------|-------|");
  for (const [i, threat] of report.threats.entries()) {
    lines.push(
      `| ${i + 1} | ${threat.title} | ${threat.strideCategory} | ${threat.affectedComponent} | **${threat.dread.total.toFixed(1)}** |`
    );
  }
  lines.push("");

  lines.push("## Threat Details");
  lines.push("");

  for (const [i, threat] of report.threats.entries()) {
    lines.push(`### ${i + 1}. ${threat.title}`);
    lines.push("");
    lines.push(`**STRIDE Category:** ${threat.strideCategory}`);
    lines.push(`**Affected Component:** ${threat.affectedComponent}`);
    lines.push(`**Attack Complexity:** ${threat.attackComplexity}`);
    lines.push("");

    lines.push("#### DREAD Scores");
    lines.push("");
    lines.push(`| Damage | Reproducibility | Exploitability | Affected Users | Discoverability | **Total** |`);
    lines.push(`|--------|-----------------|----------------|----------------|-----------------|-----------|`);
    lines.push(
      `| ${threat.dread.damage} | ${threat.dread.reproducibility} | ${threat.dread.exploitability} | ${threat.dread.affectedUsers} | ${threat.dread.discoverability} | **${threat.dread.total.toFixed(1)}** |`
    );
    lines.push("");

    lines.push("#### Attack Scenario");
    lines.push("");
    lines.push(threat.scenario);
    lines.push("");

    lines.push("#### Business Impact");
    lines.push("");
    lines.push(threat.businessImpact);
    lines.push("");

    lines.push("#### Mitigations");
    lines.push("");
    for (const mitigation of threat.mitigations) {
      lines.push(`- ${mitigation}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [ThreatLens](https://github.com/harshit/worlds-simplest-threat-modeller)*");

  return lines.join("\n");
}

export function downloadMarkdown(report: ThreatReport): void {
  const content = generateMarkdown(report);
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `threat-report-${new Date().toISOString().slice(0, 10)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
